name: Exercise 8 - Using Actions

on:
  workflow_dispatch

jobs:
  checkout-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files after checkout
        run: ls -la
