name: Exercise 7 - Variables and Secrets
on: workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My Variables
        run: echo "My name is ${{ vars.MY_NAME }}"
      - name: My Secrets
        run: echo "My name is ${{ secrets.MY_ID }}"
